@Restaurants.API_HostAddress = http://localhost:5177

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/weatherforecast/generate?count=2
Content-Type: application/json

{
    "Min":"a",
    "Max":"5"
}
###
